# Generated by Django 5.2.16 on 2026-07-22 06:55

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('event_type', models.CharField(choices=[('PLANTATION', 'Tree Plantation Drive'), ('AWARENESS', 'Awareness Campaign'), ('CLEANUP', 'Clean-up Drive'), ('CELEBRATION', 'Celebration'), ('OTHER', 'Other')], default='PLANTATION', max_length=20, verbose_name='event type')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('location_name', models.CharField(max_length=200, verbose_name='location name')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[core.validators.validate_latitude], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[core.validators.validate_longitude], verbose_name='longitude')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('max_volunteers', models.PositiveIntegerField(blank=True, help_text='Maximum number of volunteer registrations (null = unlimited).', null=True, verbose_name='max volunteers')),
                ('cover_cloudinary_id', models.CharField(blank=True, default='', max_length=255, verbose_name='cover image Cloudinary ID')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('trees_target', models.PositiveIntegerField(default=0, help_text='Number of trees planned for this event.', verbose_name='trees target')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_events', to=settings.AUTH_USER_MODEL, verbose_name='organiser')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('attended', models.BooleanField(default=False, verbose_name='attended')),
                ('trees_planted', models.PositiveIntegerField(default=0, help_text='Trees planted by this volunteer at this event.', verbose_name='trees planted')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='volunteer')),
            ],
            options={
                'verbose_name': 'event registration',
                'verbose_name_plural': 'event registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'starts_at'], name='events_even_is_publ_415ff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
