# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_gu",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_hi",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="location name"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_name_gu",
            field=models.CharField(
                max_length=200, null=True, verbose_name="location name"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_name_hi",
            field=models.CharField(
                max_length=200, null=True, verbose_name="location name"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_gu",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_hi",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
    ]
