# Generated by Django 5.1.15 on 2026-07-31 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('participation_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='participation ID')),
                ('competition_type', models.CharField(choices=[('ESSAY', 'Essay Writing'), ('DRAWING', 'Drawing Competition'), ('SUSTAINABLE_PROJECT', 'Sustainable Project Making')], max_length=30, verbose_name='competition type')),
                ('student_name', models.CharField(max_length=255, verbose_name='student name')),
                ('parent_name', models.CharField(max_length=255, verbose_name='parent / guardian name')),
                ('guardian_mobile', models.CharField(max_length=10, unique=True, verbose_name='guardian mobile number')),
                ('school_name', models.CharField(max_length=255, verbose_name='school name')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='grade / standard')),
                ('uploaded_file', models.FileField(upload_to='student_portal/works/%Y/%m/', verbose_name='uploaded work')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_portal/photos/%Y/%m/', verbose_name='student photo')),
                ('consent', models.BooleanField(default=False, verbose_name='consent provided')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for Showcase'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'student submission',
                'verbose_name_plural': 'student submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentShowcase',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('featured', models.BooleanField(default=False, verbose_name='featured entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='student_portal.studentsubmission', verbose_name='approved submission')),
            ],
            options={
                'verbose_name': 'student showcase entry',
                'verbose_name_plural': 'student showcase entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('certificate_png', models.FileField(blank=True, null=True, upload_to='student_portal/certificates/png/%Y/%m/', verbose_name='certificate PNG')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='student_portal/certificates/pdf/%Y/%m/', verbose_name='certificate PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='student_portal.studentsubmission', verbose_name='student submission')),
            ],
            options={
                'verbose_name': 'student certificate',
                'verbose_name_plural': 'student certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
