# Generated by Django 5.1.15 on 2026-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='uploaded_file',
            field=models.FileField(upload_to='student_portal/submissions/', verbose_name='uploaded work'),
        ),
    ]
