# Generated by Django 5.2.16 on 2026-07-22 06:55

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier. Must be unique.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Optional. Indian mobile number in E.164 format (+91XXXXXXXXXX).', max_length=15, null=True, unique=True, validators=[core.validators.validate_indian_phone], verbose_name='phone number')),
                ('full_name', models.CharField(help_text="User's display name.", max_length=150, verbose_name='full name')),
                ('avatar_cloudinary_id', models.CharField(blank=True, default='', help_text='Cloudinary public_id for the profile picture.', max_length=255, verbose_name='avatar Cloudinary ID')),
                ('bio', models.TextField(blank=True, default='', help_text='Short user biography (max 500 characters).', max_length=500, verbose_name='bio')),
                ('city', models.CharField(default='Naroda', help_text="User's city. Defaults to Naroda.", max_length=100, verbose_name='city')),
                ('role', models.CharField(choices=[('GUEST', 'Guest'), ('CITIZEN', 'Citizen'), ('VOLUNTEER', 'Volunteer'), ('PHOTOGRAPHER', 'Photographer'), ('COORDINATOR', 'Coordinator'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], db_index=True, default='CITIZEN', help_text="User's access role.", max_length=20, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, help_text='True when the user has confirmed their email address.', verbose_name='email verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_login_at', models.DateTimeField(blank=True, help_text="Timestamp of user's most recent successful login.", null=True, verbose_name='last login at')),
                ('notify_email', models.BooleanField(default=True, help_text='Whether to send notification emails to this user.', verbose_name='email notifications')),
                ('notify_sms', models.BooleanField(default=False, help_text='Whether to send SMS notifications to this user.', verbose_name='SMS notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('PHONE_LOGIN', 'Phone Login'), ('EMAIL_VERIFY', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset')], max_length=20, verbose_name='purpose')),
                ('code', models.CharField(help_text='6-digit one-time password.', max_length=6, verbose_name='OTP code')),
                ('is_used', models.BooleanField(default=False, help_text='True once this token has been successfully verified.', verbose_name='is used')),
                ('expires_at', models.DateTimeField(help_text='Token is invalid after this timestamp.', verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OTP token',
                'verbose_name_plural': 'OTP tokens',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='accounts_us_is_acti_0584df_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_ot_user_id_88aa89_idx'),
        ),
    ]
