# Generated by Django 5.2.16 on 2026-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='total volunteer hours'),
        ),
        migrations.AddField(
            model_name='user',
            name='trees_planted',
            field=models.PositiveIntegerField(default=0, verbose_name='trees planted'),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_level',
            field=models.CharField(choices=[('SEED', 'Seed Volunteer'), ('GREEN', 'Green Volunteer'), ('GUARDIAN', 'Tree Guardian'), ('CHAMPION', 'Nature Champion'), ('AMBASSADOR', 'Green Ambassador')], default='SEED', max_length=20, verbose_name='volunteer level'),
        ),
    ]
