# Generated by Django 5.2.16 on 2026-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_total_hours_user_trees_planted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='True when the user has confirmed their mobile phone number.', verbose_name='phone verified'),
        ),
    ]
