# Generated by Django 5.1.15 on 2026-07-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_phone_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("PHONE_LOGIN", "Phone Login"),
                    ("EMAIL_VERIFY", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("ADMIN_LOGIN", "Admin 2FA Login"),
                ],
                max_length=20,
                verbose_name="purpose",
            ),
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("PUBLISH", "Publish"),
                            ("OTP_FAILURE", "OTP Failure"),
                            ("PASSWORD_CHANGE", "Password Change"),
                        ],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="model name"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="object ID"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="details")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="user agent"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeviceFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                (
                    "user_agent",
                    models.CharField(max_length=255, verbose_name="user agent"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                (
                    "is_trusted",
                    models.BooleanField(default=True, verbose_name="is trusted"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device fingerprint",
                "verbose_name_plural": "device fingerprints",
                "unique_together": {("user", "ip_address", "user_agent")},
            },
        ),
    ]
