# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="document",
            name="title_gu",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="document",
            name="title_hi",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content_en",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content_gu",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content_hi",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="summary_en",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="summary_gu",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="summary_hi",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_gu",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_hi",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_gu",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_hi",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
    ]
