# Generated by Django 5.2.16 on 2026-07-23 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_status'),
        ('trees', '0002_tree_health_status_treemaintenancelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('certificate_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer Excellence'), ('PLANTATION', 'Tree Plantation Certificate'), ('EVENT', 'Event Participation'), ('PARTICIPATION', 'General Campaign Participation')], default='PARTICIPATION', max_length=20, verbose_name='certificate type')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='certificate number')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='events.event', verbose_name='event')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='trees.tree', verbose_name='tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
