# Generated by Django 5.1.15 on 2026-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('organization_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('SOCIETY', 'Residential Society'), ('NGO', 'NGO / Trust / Organization')], max_length=20, verbose_name='Organization Type')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration Number (optional)')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pincode')),
                ('homes_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Homes in Society')),
                ('members_participating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Members Participating')),
                ('authorized_person_name', models.CharField(max_length=255, verbose_name='Authorized Person Name')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='WhatsApp Number')),
                ('alternate_number', models.CharField(blank=True, max_length=20, verbose_name='Another Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('solar_installed', models.BooleanField(default=False, verbose_name='Is Solar Panel Installed?')),
                ('solar_panels_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Solar Panels')),
                ('rainwater_harvesting', models.BooleanField(default=False, verbose_name='Do you have Rainwater Harvesting?')),
                ('supporting_file', models.FileField(help_text='Upload Photos / Documents (JPG, PNG, PDF)', upload_to='competition/evidence/%Y/%m/', verbose_name='Supporting Evidence')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Approval Status')),
                ('registration_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Registration ID')),
            ],
            options={
                'verbose_name': 'Competition Registration',
                'verbose_name_plural': 'Competition Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
