# Generated by Django 5.1.15 on 2026-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='certificate_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/organizations/pdf/'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='certificate_png',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/organizations/png/'),
        ),
    ]
