# Generated by Django 5.1.15 on 2026-08-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_competitionregistration_certificate_generated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentialCompetitionRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "society_name",
                    models.CharField(max_length=255, verbose_name="Society Name"),
                ),
                (
                    "authorised_person_name",
                    models.CharField(
                        max_length=255, verbose_name="Authorised Person Name"
                    ),
                ),
                (
                    "authorised_person_designation",
                    models.CharField(
                        max_length=100, verbose_name="Authorised Person Designation"
                    ),
                ),
                (
                    "authorised_person_phone",
                    models.CharField(
                        max_length=20, verbose_name="Authorised Person Phone Number"
                    ),
                ),
                (
                    "trees_to_plant",
                    models.PositiveIntegerField(
                        verbose_name="Number of Trees to be Planted"
                    ),
                ),
                (
                    "members_joining",
                    models.PositiveIntegerField(
                        verbose_name="Number of Society Members Joining"
                    ),
                ),
                ("event_date", models.DateField(verbose_name="Event Date")),
            ],
            options={
                "verbose_name": "Residential Competition Registration",
                "verbose_name_plural": "Residential Competition Registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
