# Generated by Django 5.1.15 on 2026-08-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_residentialcompetitionregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResidentialCompetitionRegistration",
        ),
    ]
