# Generated by Django 5.1.15 on 2026-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_delete_residentialcompetitionregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionOrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Organization Type Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sort Order"),
                ),
            ],
            options={
                "verbose_name": "Competition Organization Type",
                "verbose_name_plural": "Competition Organization Types",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
