# Generated by Django 5.1.15 on 2026-08-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_competitionorganizationtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionregistration",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competitions.competitionorganizationtype",
                verbose_name="Organization Type",
            ),
        ),
    ]
