# Generated by Django 5.2.16 on 2026-07-22 06:55

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('name', models.CharField(help_text='Common name of the species (e.g. Neem, Peepal).', max_length=100, unique=True, verbose_name='common name')),
                ('scientific_name', models.CharField(blank=True, default='', help_text='Binomial scientific name (e.g. Azadirachta indica).', max_length=150, verbose_name='scientific name')),
                ('description', models.TextField(blank=True, default='', help_text='Brief ecological description and care notes.', verbose_name='description')),
                ('native_to_gujarat', models.BooleanField(default=False, help_text='True if this species is native to the Gujarat region.', verbose_name='native to Gujarat')),
                ('image_cloudinary_id', models.CharField(blank=True, default='', max_length=255, verbose_name='image Cloudinary ID')),
            ],
            options={
                'verbose_name': 'tree species',
                'verbose_name_plural': 'tree species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('latitude', models.FloatField(help_text='GPS latitude of planting location.', validators=[core.validators.validate_latitude], verbose_name='latitude')),
                ('longitude', models.FloatField(help_text='GPS longitude of planting location.', validators=[core.validators.validate_longitude], verbose_name='longitude')),
                ('location_name', models.CharField(blank=True, default='', help_text='Human-readable location description (e.g. Near Naroda Patiya).', max_length=200, verbose_name='location name')),
                ('ward', models.CharField(blank=True, default='', help_text='Ahmedabad Municipal Corporation ward number/name.', max_length=50, verbose_name='ward')),
                ('planted_at', models.DateField(help_text='The date this tree was physically planted.', verbose_name='planted on')),
                ('qr_code_url', models.URLField(blank=True, default='', help_text='URL to the generated QR code image for this tree.', verbose_name='QR code URL')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='verification status')),
                ('growth_stage', models.CharField(choices=[('SAPLING', 'Sapling'), ('YOUNG', 'Young Tree'), ('MATURE', 'Mature Tree')], default='SAPLING', max_length=10, verbose_name='growth stage')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this tree (e.g. care instructions, soil type).', verbose_name='notes')),
                ('contributor', models.ForeignKey(blank=True, help_text='The person who sponsored/registered this tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_trees', to=settings.AUTH_USER_MODEL, verbose_name='contributor')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='events.event', verbose_name='planting event')),
                ('planted_by', models.ForeignKey(blank=True, help_text='The volunteer who physically planted the tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_trees', to=settings.AUTH_USER_MODEL, verbose_name='planted by')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trees', to='trees.treespecies', verbose_name='species')),
            ],
            options={
                'verbose_name': 'tree',
                'verbose_name_plural': 'trees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='decision')),
                ('notes', models.TextField(blank=True, default='', help_text="Coordinator's field notes about this verification.", verbose_name='verification notes')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='trees.tree', verbose_name='tree')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_verifications', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'tree verification',
                'verbose_name_plural': 'tree verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('cloudinary_id', models.CharField(help_text='Cloudinary public_id for the photo.', max_length=255, verbose_name='Cloudinary ID')),
                ('cloudinary_url', models.URLField(help_text='Optimised delivery URL from Cloudinary.', verbose_name='Cloudinary URL')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='caption')),
                ('taken_at', models.DateField(blank=True, help_text='Date the photograph was taken (from EXIF if available).', null=True, verbose_name='taken on')),
                ('is_primary', models.BooleanField(default=False, help_text='The primary display photo for this tree.', verbose_name='is primary')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trees.tree', verbose_name='tree')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_photos', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'tree photo',
                'verbose_name_plural': 'tree photos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tree',), name='unique_primary_photo_per_tree')],
            },
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['verification_status'], name='trees_tree_verific_f14df6_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['planted_at'], name='trees_tree_planted_c96efe_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['ward'], name='trees_tree_ward_d264da_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['contributor'], name='trees_tree_contrib_38ac02_idx'),
        ),
    ]
