# Generated by Django 5.2.16 on 2026-07-22 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='health_status',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor'), ('DEAD', 'Dead')], default='GOOD', max_length=20, verbose_name='health status'),
        ),
        migrations.CreateModel(
            name='TreeMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('issue_type', models.CharField(choices=[('WATER', 'Needs Water'), ('SUPPORT', 'Needs Support'), ('DISEASE', 'Disease Reported'), ('FENCE', 'Fence Broken'), ('REPLACEMENT', 'Replacement Needed'), ('OTHER', 'Other')], max_length=20, verbose_name='issue type')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='reported by')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='trees.tree', verbose_name='tree')),
            ],
            options={
                'verbose_name': 'maintenance log',
                'verbose_name_plural': 'maintenance logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
