# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_tree_health_status_treemaintenancelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="location_name_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable location description (e.g. Near Naroda Patiya).",
                max_length=200,
                null=True,
                verbose_name="location name",
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="location_name_gu",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable location description (e.g. Near Naroda Patiya).",
                max_length=200,
                null=True,
                verbose_name="location name",
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="location_name_hi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable location description (e.g. Near Naroda Patiya).",
                max_length=200,
                null=True,
                verbose_name="location name",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief ecological description and care notes.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="description_gu",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief ecological description and care notes.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="description_hi",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief ecological description and care notes.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="name_en",
            field=models.CharField(
                help_text="Common name of the species (e.g. Neem, Peepal).",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="common name",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="name_gu",
            field=models.CharField(
                help_text="Common name of the species (e.g. Neem, Peepal).",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="common name",
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="name_hi",
            field=models.CharField(
                help_text="Common name of the species (e.g. Neem, Peepal).",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="common name",
            ),
        ),
    ]
