# Generated by Django 5.1.15 on 2026-07-24 17:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PledgeRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                        verbose_name="mobile number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                ("ward", models.CharField(max_length=100, verbose_name="ward / area")),
                ("address", models.TextField(verbose_name="address")),
                (
                    "city",
                    models.CharField(
                        default="Ahmedabad", max_length=100, verbose_name="city"
                    ),
                ),
                ("pincode", models.CharField(max_length=10, verbose_name="pincode")),
                ("age", models.PositiveIntegerField(verbose_name="age")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "trees_to_adopt",
                    models.PositiveIntegerField(
                        default=1, verbose_name="trees to adopt"
                    ),
                ),
                (
                    "plantation_interest",
                    models.CharField(
                        choices=[
                            ("PLANTING", "Planting Trees"),
                            ("ADOPTING", "Adopting & Caring for Trees"),
                            ("BOTH", "Both Planting and Adopting"),
                            ("VOLUNTEER", "General Volunteer"),
                        ],
                        max_length=50,
                        verbose_name="plantation interest",
                    ),
                ),
                (
                    "agreed_to_pledge",
                    models.BooleanField(default=True, verbose_name="agreed to pledge"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="is approved"),
                ),
            ],
            options={
                "verbose_name": "pledge registration",
                "verbose_name_plural": "pledge registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
