# Generated by Django 5.1.15 on 2026-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledgeregistration",
            name="certificate_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="certificates/",
                verbose_name="certificate image",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="certificate_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="certificate number",
            ),
        ),
    ]
