# Generated by Django 5.1.15 on 2026-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_pledgeregistration_certificate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledgeregistration",
            name="browser_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="certificate_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificates/pdfs/",
                verbose_name="certificate pdf",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="share_fb_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="share_ig_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="share_wa_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
