# Generated by Django 5.1.15 on 2026-07-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0003_pledgeregistration_browser_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="area name")),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, null=True, verbose_name="area name"
                    ),
                ),
                (
                    "name_gu",
                    models.CharField(
                        max_length=150, null=True, verbose_name="area name"
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        max_length=150, null=True, verbose_name="area name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
                "ordering": ["ward__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="organization name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="organization name",
                    ),
                ),
                (
                    "name_gu",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="organization name",
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="organization name",
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT", "Government"),
                            ("PRIVATE", "Private"),
                            ("NGO", "NGO"),
                            ("EDUCATIONAL", "Educational"),
                            ("CORPORATE", "Corporate"),
                            ("VOLUNTEER_GROUP", "Volunteer Group"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=50,
                        verbose_name="organization type",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/",
                        verbose_name="organization logo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ward name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="ward name"
                    ),
                ),
                (
                    "name_gu",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="ward name"
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="ward name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "ward",
                "verbose_name_plural": "wards",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="city",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="plantation_interest",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="trees_to_adopt",
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="consent_accepted",
            field=models.BooleanField(default=True, verbose_name="consent accepted"),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01", verbose_name="date of birth"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="otp_verified",
            field=models.BooleanField(default=False, verbose_name="otp verified"),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="calculated age"
            ),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT", "Prefer Not to Say"),
                ],
                max_length=20,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="volunteers.area",
                verbose_name="area",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="volunteers.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="volunteers.ward",
                verbose_name="ward",
            ),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="volunteers.ward",
                verbose_name="ward",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="area",
            unique_together={
                ("ward", "name"),
                ("ward", "name_en"),
                ("ward", "name_gu"),
                ("ward", "name_hi"),
            },
        ),
    ]
