# Generated by Django 5.1.15 on 2026-07-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0004_area_organization_ward_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="area",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="ward",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="address",
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="volunteers.organization",
                verbose_name="organization",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.DeleteModel(
            name="Ward",
        ),
    ]
