# Generated by Django 5.1.15 on 2026-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_remove_pledgeregistration_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledgeregistration",
            name="city",
            field=models.CharField(
                default="Ahmedabad", max_length=100, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="pincode",
            field=models.CharField(
                default="382330", max_length=10, verbose_name="pincode"
            ),
        ),
    ]
