# Generated by Django 5.1.15 on 2026-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0006_pledgeregistration_city_pledgeregistration_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledgeregistration",
            name="whatsapp_status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
