# Generated by Django 5.1.15 on 2026-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0007_pledgeregistration_whatsapp_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="certificate_number",
        ),
        migrations.RemoveField(
            model_name="pledgeregistration",
            name="whatsapp_status",
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="certificate_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="certificate id",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="whatsapp_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="certificate_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="certificates/images/",
                verbose_name="certificate image",
            ),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="is approved"),
        ),
        migrations.AlterField(
            model_name="pledgeregistration",
            name="otp_verified",
            field=models.BooleanField(default=True, verbose_name="otp verified"),
        ),
    ]
