# Generated by Django 5.1.15 on 2026-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0008_remove_pledgeregistration_certificate_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="sort order"),
        ),
    ]
