# Generated by Django 5.1.15 on 2026-08-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0009_organization_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreedomFighterName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="freedom fighter name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "used_in_current_cycle",
                    models.BooleanField(
                        default=False, verbose_name="used in current cycle"
                    ),
                ),
            ],
            options={
                "verbose_name": "freedom fighter name",
                "verbose_name_plural": "freedom fighter names",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="tree_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="tree number",
            ),
        ),
        migrations.AddField(
            model_name="pledgeregistration",
            name="dedicated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dedicated_trees",
                to="volunteers.freedomfightername",
                verbose_name="dedicated to freedom fighter",
            ),
        ),
    ]
