import os
from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import UUIDSoftDeleteModel

class MediaAsset(UUIDSoftDeleteModel):
    """
    Centralized Media Asset for the Government CMS.
    Every image uploaded to the website should go through this model,
    enabling a single media library for previews, replacements, and global updates.
    """
    class AssetCategory(models.TextChoices):
        HERO = "HERO", _("Hero Images")
        MISSION = "MISSION", _("Mission Images")
        GALLERY = "GALLERY", _("Gallery Images")
        CAMPAIGN = "CAMPAIGN", _("Campaign Images")
        BACKGROUND = "BACKGROUND", _("Background Images")
        CERTIFICATE = "CERTIFICATE", _("Certificates")
        NEWS = "NEWS", _("News Images")
        OTHER = "OTHER", _("Other")

    category = models.CharField(_("category"), max_length=50, choices=AssetCategory.choices, default=AssetCategory.OTHER)
    title = models.CharField(_("title"), max_length=200, help_text=_("Internal title or caption"))
    image = models.ImageField(_("image"), upload_to="cms/media/%Y/%m/")
    alt_text = models.CharField(_("alt text"), max_length=255, blank=True, help_text=_("For SEO and Accessibility"))
    credits = models.CharField(_("credits"), max_length=150, blank=True)
    tags = models.CharField(_("tags"), max_length=255, blank=True, help_text=_("Comma separated tags for search"))
    
    # Auto-generated by signals or property
    file_size = models.PositiveIntegerField(_("file size (bytes)"), null=True, blank=True, editable=False)
    
    class Meta:
        verbose_name = _("media asset")
        verbose_name_plural = _("media library")
        ordering = ["-created_at"]

    def __str__(self):
        if self.image and hasattr(self.image, 'name') and self.image.name:
            return self.title or os.path.basename(self.image.name)
        return self.title or "Empty Asset"
