# Generated by Django 5.2.16 on 2026-07-22 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'gallery category',
                'verbose_name_plural': 'gallery categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'photo tag',
                'verbose_name_plural': 'photo tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique public identifier for this record.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('cloudinary_id', models.CharField(help_text='Cloudinary public_id for the original image.', max_length=255, verbose_name='Cloudinary ID')),
                ('url', models.URLField(help_text='Cloudinary delivery URL for the full-size image.', verbose_name='URL')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Cloudinary URL for 400px thumbnail (auto-generated).', verbose_name='thumbnail URL')),
                ('webp_url', models.URLField(blank=True, default='', help_text='Cloudinary WebP format URL for modern browsers.', verbose_name='WebP URL')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='width')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='height')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='taken on')),
                ('exif_data', models.JSONField(blank=True, default=dict, help_text='Raw EXIF metadata extracted at upload time.', verbose_name='EXIF data')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='approval status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured photos appear in homepage preview.', verbose_name='featured')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this photo has been viewed.', verbose_name='view count')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_photos', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='gallery.gallerycategory', verbose_name='category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='events.event', verbose_name='associated event')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='photographer')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='gallery.phototag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status', 'is_featured'], name='gallery_pho_approva_274e69_idx'), models.Index(fields=['photographer'], name='gallery_pho_photogr_43ba97_idx'), models.Index(fields=['category'], name='gallery_pho_categor_fd1951_idx'), models.Index(fields=['taken_at'], name='gallery_pho_taken_a_4ce4df_idx')],
            },
        ),
    ]
