# Generated by Django 5.2.16 on 2026-07-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DRONE', 'Drone Photo'), ('VIDEO', 'Video'), ('PANORAMA', '360 Panorama')], default='IMAGE', max_length=20, verbose_name='media type'),
        ),
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_collections', to='gallery.photo', verbose_name='cover photo')),
                ('photos', models.ManyToManyField(blank=True, related_name='collections', to='gallery.photo', verbose_name='photos')),
            ],
            options={
                'verbose_name': 'gallery collection',
                'verbose_name_plural': 'gallery collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
