# Generated by Django 5.2.16 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_media_type_gallerycollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='local_image',
            field=models.ImageField(blank=True, help_text='Direct file upload stored locally (used when Cloudinary is not configured).', null=True, upload_to='gallery/uploads/%Y/%m/', verbose_name='uploaded image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cloudinary_id',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id for the original image.', max_length=255, verbose_name='Cloudinary ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary delivery URL for the full-size image.', verbose_name='URL'),
        ),
    ]
