# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_add_local_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerycategory",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycategory",
            name="description_gu",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycategory",
            name="description_hi",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycategory",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="gallerycategory",
            name="name_gu",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="gallerycategory",
            name="name_hi",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="description_gu",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="description_hi",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="title_gu",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="gallerycollection",
            name="title_hi",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="photo",
            name="location_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="location_gu",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="location_hi",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="title_gu",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="title_hi",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="title"
            ),
        ),
    ]
