# Generated by Django 5.2.16 on 2026-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('question_en', models.CharField(max_length=300, verbose_name='question (English)')),
                ('question_gu', models.CharField(blank=True, default='', max_length=300, verbose_name='question (Gujarati)')),
                ('question_hi', models.CharField(blank=True, default='', max_length=300, verbose_name='question (Hindi)')),
                ('answer_en', models.TextField(verbose_name='answer (English)')),
                ('answer_gu', models.TextField(blank=True, default='', verbose_name='answer (Gujarati)')),
                ('answer_hi', models.TextField(blank=True, default='', verbose_name='answer (Hindi)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('logo_cloudinary_id', models.CharField(max_length=255, verbose_name='logo Cloudinary ID')),
                ('website_url', models.URLField(blank=True, default='', verbose_name='website')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('trees_planted', models.PositiveIntegerField(default=0, verbose_name='trees planted')),
                ('volunteers_count', models.PositiveIntegerField(default=0, verbose_name='volunteers count')),
                ('events_count', models.PositiveIntegerField(default=0, verbose_name='events count')),
                ('photos_count', models.PositiveIntegerField(default=0, verbose_name='photos count')),
                ('hero_tagline_en', models.CharField(default='28,855 Days of Independence. 28,855 Trees for Tomorrow.', max_length=200, verbose_name='hero tagline (English)')),
                ('hero_tagline_gu', models.CharField(default='સ્વતંત્રતાના ૨૮,૮૫૫ દિવસ. આવતીકાલ માટે ૨૮,૮૫૫ વૃક્ષ.', max_length=200, verbose_name='hero tagline (Gujarati)')),
                ('hero_tagline_hi', models.CharField(default='स्वतंत्रता के 28,855 दिन। कल के लिए 28,855 पेड़।', max_length=200, verbose_name='hero tagline (Hindi)')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter/X URL')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube URL')),
                ('contact_email', models.EmailField(default='hello@mynaroda.in', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='contact phone')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created (UTC).', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified (UTC).', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('role', models.CharField(default='Volunteer', help_text="e.g. 'Tree Plantation Volunteer' or 'Naroda Resident'", max_length=100, verbose_name='role')),
                ('quote_en', models.TextField(max_length=500, verbose_name='quote (English)')),
                ('quote_gu', models.TextField(blank=True, default='', max_length=500, verbose_name='quote (Gujarati)')),
                ('quote_hi', models.TextField(blank=True, default='', max_length=500, verbose_name='quote (Hindi)')),
                ('avatar_cloudinary_id', models.CharField(blank=True, default='', max_length=255, verbose_name='avatar Cloudinary ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
