# Generated by Django 5.1.15 on 2026-07-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="campaign_title",
            field=models.CharField(
                default="Registration for Tree Plantation & Adoption Pledge",
                max_length=200,
                verbose_name="campaign title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_trees_per_registrant",
            field=models.PositiveIntegerField(
                default=10, verbose_name="max trees per registrant"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_delay_seconds",
            field=models.PositiveIntegerField(
                default=5, verbose_name="popup delay (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_enabled",
            field=models.BooleanField(default=True, verbose_name="popup enabled"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_frequency",
            field=models.CharField(
                choices=[("SESSION", "Once per session"), ("ALWAYS", "On every visit")],
                default="SESSION",
                max_length=20,
                verbose_name="popup frequency",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_message",
            field=models.TextField(
                default="Join the Green Naroda • Clean Naroda Mission and contribute towards planting 28,855 trees for India's 80th Independence Year.",
                verbose_name="popup message",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_dates",
            field=models.CharField(
                default="1–7 August", max_length=100, verbose_name="registration dates"
            ),
        ),
    ]
