# Generated by Django 5.1.15 on 2026-07-27 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_sitesettings_campaign_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique public identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title or caption",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/media/%Y/%m/", verbose_name="image"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="For SEO and Accessibility",
                        max_length=255,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "credits",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="credits"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated tags for search",
                        max_length=255,
                        verbose_name="tags",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="file size (bytes)",
                    ),
                ),
            ],
            options={
                "verbose_name": "media asset",
                "verbose_name_plural": "media library",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="page title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "hero_title",
                    models.CharField(max_length=150, verbose_name="hero title"),
                ),
                (
                    "hero_subtitle",
                    models.CharField(max_length=200, verbose_name="hero subtitle"),
                ),
                (
                    "hero_description",
                    models.TextField(blank=True, verbose_name="hero description"),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="Mission Introduction",
                        max_length=150,
                        verbose_name="intro title",
                    ),
                ),
                ("intro_text_1", models.TextField(verbose_name="intro paragraph 1")),
                (
                    "intro_text_2",
                    models.TextField(blank=True, verbose_name="intro paragraph 2"),
                ),
                (
                    "vision_title",
                    models.CharField(
                        default="The Vision",
                        max_length=150,
                        verbose_name="vision title",
                    ),
                ),
                ("vision_text", models.TextField(verbose_name="vision description")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta description"),
                ),
                (
                    "hero_background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hero_pages",
                        to="cms.mediaasset",
                        verbose_name="hero background",
                    ),
                ),
                (
                    "intro_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intro_pages",
                        to="cms.mediaasset",
                        verbose_name="intro image",
                    ),
                ),
                (
                    "vision_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vision_pages",
                        to="cms.mediaasset",
                        verbose_name="vision image",
                    ),
                ),
            ],
            options={
                "verbose_name": "mission page",
                "verbose_name_plural": "mission pages",
            },
        ),
        migrations.CreateModel(
            name="PageHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="Ongoing Action",
                        max_length=50,
                        verbose_name="badge text",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlights",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="cms.pagemission",
                    ),
                ),
            ],
            options={
                "verbose_name": "mission highlight",
                "verbose_name_plural": "mission highlights",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PageActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "button_text",
                    models.CharField(
                        default="Learn More", max_length=50, verbose_name="button text"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="cms.pagemission",
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign activity",
                "verbose_name_plural": "campaign activities",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PageObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="cms.pagemission",
                    ),
                ),
            ],
            options={
                "verbose_name": "objective",
                "verbose_name_plural": "objectives",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PageStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=50, verbose_name="value (e.g. 100%)"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statistics",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="cms.pagemission",
                    ),
                ),
            ],
            options={
                "verbose_name": "impact statistic",
                "verbose_name_plural": "impact statistics",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PageTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(verbose_name="step number"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active step"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timelines",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelines",
                        to="cms.pagemission",
                    ),
                ),
            ],
            options={
                "verbose_name": "timeline step",
                "verbose_name_plural": "timeline steps",
                "ordering": ["sort_order", "step_number"],
            },
        ),
    ]
