# Generated by Django 5.1.15 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_mediaasset_pagemission_pagehighlight_pageactivity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("HERO", "Hero Images"),
                    ("MISSION", "Mission Images"),
                    ("GALLERY", "Gallery Images"),
                    ("CAMPAIGN", "Campaign Images"),
                    ("BACKGROUND", "Background Images"),
                    ("CERTIFICATE", "Certificates"),
                    ("NEWS", "News Images"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="category",
            ),
        ),
    ]
