# Generated by Django 5.1.15 on 2026-07-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_mediaasset_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "target_trees",
                    models.PositiveIntegerField(
                        default=28855, verbose_name="target trees"
                    ),
                ),
                (
                    "trees_planted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="trees planted"
                    ),
                ),
                (
                    "citizens_joined",
                    models.PositiveIntegerField(
                        default=0, verbose_name="citizens joined"
                    ),
                ),
                (
                    "wards_covered",
                    models.PositiveIntegerField(
                        default=14, verbose_name="wards covered"
                    ),
                ),
                (
                    "co2_saved_kg",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CO2 saved (kg)"
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign progress",
                "verbose_name_plural": "campaign progress",
            },
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="CELEBRATING INDIA'S 80TH INDEPENDENCE YEAR",
                        max_length=150,
                        verbose_name="hero title",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="PLANTING 28,855 TREES",
                        max_length=200,
                        verbose_name="hero subtitle",
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(blank=True, verbose_name="hero description"),
                ),
                (
                    "green_card_title",
                    models.CharField(
                        default="Green Naroda",
                        max_length=100,
                        verbose_name="green card title",
                    ),
                ),
                (
                    "green_card_text",
                    models.TextField(blank=True, verbose_name="green card description"),
                ),
                (
                    "clean_card_title",
                    models.CharField(
                        default="Clean Naroda",
                        max_length=100,
                        verbose_name="clean card title",
                    ),
                ),
                (
                    "clean_card_text",
                    models.TextField(blank=True, verbose_name="clean card description"),
                ),
                (
                    "clean_card_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_clean_card",
                        to="cms.mediaasset",
                        verbose_name="clean card image",
                    ),
                ),
                (
                    "green_card_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_green_card",
                        to="cms.mediaasset",
                        verbose_name="green card image",
                    ),
                ),
                (
                    "hero_background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_hero",
                        to="cms.mediaasset",
                        verbose_name="hero background",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage content",
                "verbose_name_plural": "homepage content",
            },
        ),
    ]
