# Generated by Django 5.1.15 on 2026-07-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_campaignprogress_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="headline")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="subtitle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "primary_button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="primary button text"
                    ),
                ),
                (
                    "primary_button_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="primary button URL"
                    ),
                ),
                (
                    "secondary_button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="secondary button text"
                    ),
                ),
                (
                    "secondary_button_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="secondary button URL"
                    ),
                ),
                (
                    "overlay_color",
                    models.CharField(
                        choices=[
                            ("bg-green-900", "Dark Green"),
                            ("bg-orange-900", "Dark Orange"),
                            ("bg-black", "Black"),
                        ],
                        default="bg-black",
                        max_length=50,
                        verbose_name="overlay color",
                    ),
                ),
                (
                    "overlay_opacity",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="e.g. 50 for 50% opacity.",
                        verbose_name="overlay opacity (0-100)",
                    ),
                ),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("ken-burns-zoom-in", "Ken Burns Zoom In"),
                            ("ken-burns-zoom-out", "Ken Burns Zoom Out"),
                            ("pan-left", "Pan Left"),
                            ("pan-right", "Pan Right"),
                            ("zoom-pan-left", "Zoom + Pan Left"),
                            ("zoom-pan-right", "Zoom + Pan Right"),
                            ("static", "Static"),
                        ],
                        default="ken-burns-zoom-in",
                        max_length=50,
                        verbose_name="animation type",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="PUBLISHED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "desktop_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_desktop",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_slides",
                        to="cms.homepage",
                    ),
                ),
                (
                    "mobile_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. Used for mobile devices.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slide_mobile",
                        to="cms.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "hero slide",
                "verbose_name_plural": "hero slides",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
