# Generated by Django 5.1.15 on 2026-07-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_heroslide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroslide",
            name="animation_type",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="desktop_image",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="mobile_image",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="overlay_color",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="overlay_opacity",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="publish_status",
        ),
        migrations.AddField(
            model_name="heroslide",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_slides",
                to="cms.mediaasset",
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="mission_type",
            field=models.CharField(
                choices=[("GREEN", "Green Mission"), ("CLEAN", "Clean Mission")],
                default="GREEN",
                max_length=20,
                verbose_name="mission type",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="primary_button_text",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="button 1 text"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="primary_button_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="button 1 URL"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="secondary_button_text",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="button 2 text"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="secondary_button_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="button 2 URL"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="display order"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="title",
            field=models.CharField(max_length=150, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                default="prathampriority@mynaroda.in",
                max_length=254,
                verbose_name="contact email",
            ),
        ),
    ]
