# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_remove_heroslide_animation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer",
            field=models.TextField(default="", verbose_name="answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question",
            field=models.CharField(default="", max_length=300, verbose_name="question"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="description_gu",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="description_hi",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="primary_button_text_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 1 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="primary_button_text_gu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 1 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="primary_button_text_hi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 1 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="secondary_button_text_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 2 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="secondary_button_text_gu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 2 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="secondary_button_text_hi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="button 2 text"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="subtitle_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="subtitle"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="subtitle_gu",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="subtitle"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="subtitle_hi",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="subtitle"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_en",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_gu",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_hi",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="clean card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_text_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="clean card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_text_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="clean card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_title_en",
            field=models.CharField(
                default="Clean Naroda",
                max_length=100,
                null=True,
                verbose_name="clean card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_title_gu",
            field=models.CharField(
                default="Clean Naroda",
                max_length=100,
                null=True,
                verbose_name="clean card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="clean_card_title_hi",
            field=models.CharField(
                default="Clean Naroda",
                max_length=100,
                null=True,
                verbose_name="clean card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="green card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_text_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="green card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_text_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="green card description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_title_en",
            field=models.CharField(
                default="Green Naroda",
                max_length=100,
                null=True,
                verbose_name="green card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_title_gu",
            field=models.CharField(
                default="Green Naroda",
                max_length=100,
                null=True,
                verbose_name="green card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="green_card_title_hi",
            field=models.CharField(
                default="Green Naroda",
                max_length=100,
                null=True,
                verbose_name="green card title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_description_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_description_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle_en",
            field=models.CharField(
                default="PLANTING 28,855 TREES",
                max_length=200,
                null=True,
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle_gu",
            field=models.CharField(
                default="PLANTING 28,855 TREES",
                max_length=200,
                null=True,
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle_hi",
            field=models.CharField(
                default="PLANTING 28,855 TREES",
                max_length=200,
                null=True,
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title_en",
            field=models.CharField(
                default="CELEBRATING INDIA'S 80TH INDEPENDENCE YEAR",
                max_length=150,
                null=True,
                verbose_name="hero title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title_gu",
            field=models.CharField(
                default="CELEBRATING INDIA'S 80TH INDEPENDENCE YEAR",
                max_length=150,
                null=True,
                verbose_name="hero title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title_hi",
            field=models.CharField(
                default="CELEBRATING INDIA'S 80TH INDEPENDENCE YEAR",
                max_length=150,
                null=True,
                verbose_name="hero title",
            ),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="button_text_en",
            field=models.CharField(
                default="Learn More",
                max_length=50,
                null=True,
                verbose_name="button text",
            ),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="button_text_gu",
            field=models.CharField(
                default="Learn More",
                max_length=50,
                null=True,
                verbose_name="button text",
            ),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="button_text_hi",
            field=models.CharField(
                default="Learn More",
                max_length=50,
                null=True,
                verbose_name="button text",
            ),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="description_en",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="description_gu",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="description_hi",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="title_en",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="title_gu",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pageactivity",
            name="title_hi",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="badge_text_en",
            field=models.CharField(
                default="Ongoing Action",
                max_length=50,
                null=True,
                verbose_name="badge text",
            ),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="badge_text_gu",
            field=models.CharField(
                default="Ongoing Action",
                max_length=50,
                null=True,
                verbose_name="badge text",
            ),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="badge_text_hi",
            field=models.CharField(
                default="Ongoing Action",
                max_length=50,
                null=True,
                verbose_name="badge text",
            ),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="description_en",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="description_gu",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="description_hi",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="title_en",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="title_gu",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagehighlight",
            name="title_hi",
            field=models.CharField(max_length=150, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_description_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_description_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="hero description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_subtitle_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="hero subtitle"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_subtitle_gu",
            field=models.CharField(
                max_length=200, null=True, verbose_name="hero subtitle"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_subtitle_hi",
            field=models.CharField(
                max_length=200, null=True, verbose_name="hero subtitle"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_title_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="hero title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_title_gu",
            field=models.CharField(
                max_length=150, null=True, verbose_name="hero title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="hero_title_hi",
            field=models.CharField(
                max_length=150, null=True, verbose_name="hero title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_1_en",
            field=models.TextField(null=True, verbose_name="intro paragraph 1"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_1_gu",
            field=models.TextField(null=True, verbose_name="intro paragraph 1"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_1_hi",
            field=models.TextField(null=True, verbose_name="intro paragraph 1"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_2_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="intro paragraph 2"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_2_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="intro paragraph 2"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_text_2_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="intro paragraph 2"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_title_en",
            field=models.CharField(
                default="Mission Introduction",
                max_length=150,
                null=True,
                verbose_name="intro title",
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_title_gu",
            field=models.CharField(
                default="Mission Introduction",
                max_length=150,
                null=True,
                verbose_name="intro title",
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="intro_title_hi",
            field=models.CharField(
                default="Mission Introduction",
                max_length=150,
                null=True,
                verbose_name="intro title",
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="meta description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_description_gu",
            field=models.TextField(
                blank=True, null=True, verbose_name="meta description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_description_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="meta description"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_title_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="meta title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_title_gu",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="meta title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="meta_title_hi",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="meta title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="title_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="page title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="title_gu",
            field=models.CharField(
                max_length=100, null=True, verbose_name="page title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="title_hi",
            field=models.CharField(
                max_length=100, null=True, verbose_name="page title"
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_text_en",
            field=models.TextField(null=True, verbose_name="vision description"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_text_gu",
            field=models.TextField(null=True, verbose_name="vision description"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_text_hi",
            field=models.TextField(null=True, verbose_name="vision description"),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_title_en",
            field=models.CharField(
                default="The Vision",
                max_length=150,
                null=True,
                verbose_name="vision title",
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_title_gu",
            field=models.CharField(
                default="The Vision",
                max_length=150,
                null=True,
                verbose_name="vision title",
            ),
        ),
        migrations.AddField(
            model_name="pagemission",
            name="vision_title_hi",
            field=models.CharField(
                default="The Vision",
                max_length=150,
                null=True,
                verbose_name="vision title",
            ),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="description_en",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="description_gu",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="description_hi",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="title_gu",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pageobjective",
            name="title_hi",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="label_en",
            field=models.CharField(max_length=100, null=True, verbose_name="label"),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="label_gu",
            field=models.CharField(max_length=100, null=True, verbose_name="label"),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="label_hi",
            field=models.CharField(max_length=100, null=True, verbose_name="label"),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="value_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="value (e.g. 100%)"
            ),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="value_gu",
            field=models.CharField(
                max_length=50, null=True, verbose_name="value (e.g. 100%)"
            ),
        ),
        migrations.AddField(
            model_name="pagestatistic",
            name="value_hi",
            field=models.CharField(
                max_length=50, null=True, verbose_name="value (e.g. 100%)"
            ),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="description_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="description_gu",
            field=models.CharField(
                max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="description_hi",
            field=models.CharField(
                max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="title_gu",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="pagetimeline",
            name="title_hi",
            field=models.CharField(max_length=100, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="campaign_title_en",
            field=models.CharField(
                default="Registration for Tree Plantation & Adoption Pledge",
                max_length=200,
                null=True,
                verbose_name="campaign title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="campaign_title_gu",
            field=models.CharField(
                default="Registration for Tree Plantation & Adoption Pledge",
                max_length=200,
                null=True,
                verbose_name="campaign title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="campaign_title_hi",
            field=models.CharField(
                default="Registration for Tree Plantation & Adoption Pledge",
                max_length=200,
                null=True,
                verbose_name="campaign title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_tagline",
            field=models.CharField(
                default="28,855 Days of Independence. 28,855 Trees for Tomorrow.",
                max_length=200,
                verbose_name="hero tagline",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_message_en",
            field=models.TextField(
                default="Join the Green Naroda • Clean Naroda Mission and contribute towards planting 28,855 trees for India's 80th Independence Year.",
                null=True,
                verbose_name="popup message",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_message_gu",
            field=models.TextField(
                default="Join the Green Naroda • Clean Naroda Mission and contribute towards planting 28,855 trees for India's 80th Independence Year.",
                null=True,
                verbose_name="popup message",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="popup_message_hi",
            field=models.TextField(
                default="Join the Green Naroda • Clean Naroda Mission and contribute towards planting 28,855 trees for India's 80th Independence Year.",
                null=True,
                verbose_name="popup message",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="quote",
            field=models.TextField(default="", max_length=500, verbose_name="quote"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_en",
            field=models.CharField(
                default="Volunteer",
                help_text="e.g. 'Tree Plantation Volunteer' or 'Naroda Resident'",
                max_length=100,
                null=True,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_gu",
            field=models.CharField(
                default="Volunteer",
                help_text="e.g. 'Tree Plantation Volunteer' or 'Naroda Resident'",
                max_length=100,
                null=True,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_hi",
            field=models.CharField(
                default="Volunteer",
                help_text="e.g. 'Tree Plantation Volunteer' or 'Naroda Resident'",
                max_length=100,
                null=True,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(default="", null=True, verbose_name="answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_gu",
            field=models.TextField(default="", null=True, verbose_name="answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=models.TextField(default="", null=True, verbose_name="answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_en",
            field=models.CharField(
                default="", max_length=300, null=True, verbose_name="question"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_gu",
            field=models.CharField(
                default="", max_length=300, null=True, verbose_name="question"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.CharField(
                default="", max_length=300, null=True, verbose_name="question"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_tagline_en",
            field=models.CharField(
                default="28,855 Days of Independence. 28,855 Trees for Tomorrow.",
                max_length=200,
                null=True,
                verbose_name="hero tagline",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_tagline_gu",
            field=models.CharField(
                default="28,855 Days of Independence. 28,855 Trees for Tomorrow.",
                max_length=200,
                null=True,
                verbose_name="hero tagline",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_tagline_hi",
            field=models.CharField(
                default="28,855 Days of Independence. 28,855 Trees for Tomorrow.",
                max_length=200,
                null=True,
                verbose_name="hero tagline",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_en",
            field=models.TextField(
                default="", max_length=500, null=True, verbose_name="quote"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_gu",
            field=models.TextField(
                default="", max_length=500, null=True, verbose_name="quote"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_hi",
            field=models.TextField(
                default="", max_length=500, null=True, verbose_name="quote"
            ),
        ),
    ]
