# Generated by Django 5.1.15 on 2026-08-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_heroslide_image_en_heroslide_image_gu_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
