# Generated by Django 5.1.15 on 2026-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_delete_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "nitin_nabin",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "bhupendrabhai_patel",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "jagdish_vishwakarma",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "harshbhai_sanghavi",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "ratnakarji",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "ajay_brahmbhatt",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "anirudhbhai_dave",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "prashantbhai_korat",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "hitendrasinh_chauhan",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "prerakbhai_shah",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "hasmukhbhai_patel",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "dineshbhai_makwana",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
            ],
            options={
                "verbose_name": "Leadership Photos",
                "verbose_name_plural": "Leadership Photos",
            },
        ),
    ]
