# Generated by Django 5.1.15 on 2026-08-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_leadershipphotos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="ajay_brahmbhatt",
            new_name="ajay_brahmbhatt_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="anirudhbhai_dave",
            new_name="anirudhbhai_dave_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="bhupendrabhai_patel",
            new_name="bhupendrabhai_patel_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="dineshbhai_makwana",
            new_name="dineshbhai_makwana_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="harshbhai_sanghavi",
            new_name="harshbhai_sanghavi_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="hasmukhbhai_patel",
            new_name="hasmukhbhai_patel_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="hitendrasinh_chauhan",
            new_name="hitendrasinh_chauhan_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="jagdish_vishwakarma",
            new_name="jagdish_vishwakarma_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="nitin_nabin",
            new_name="nitin_nabin_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="prashantbhai_korat",
            new_name="prashantbhai_korat_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="prerakbhai_shah",
            new_name="prerakbhai_shah_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="ratnakarji",
            new_name="ratnakarji_photo",
        ),
    ]
