# Generated by Django 5.1.15 on 2026-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms",
            "0013_rename_ajay_brahmbhatt_leadershipphotos_ajay_brahmbhatt_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipphotos",
            name="nikunj_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="payalben_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
    ]
