# Generated by Django 5.1.15 on 2026-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_leadershipphotos_nikunj_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "my_naroda_logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "bjp_logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "pratham_logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "gncn_logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
            ],
            options={
                "verbose_name": "branding settings",
                "verbose_name_plural": "branding settings",
            },
        ),
    ]
