# Generated by Django 5.1.15 on 2026-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_brandingsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarGharTirangaRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="full name")),
                (
                    "mobile_number",
                    models.CharField(max_length=15, verbose_name="mobile number"),
                ),
                ("address", models.TextField(verbose_name="address")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="location text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Har Ghar Tiranga registration",
                "verbose_name_plural": "Har Ghar Tiranga registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
