# Generated by Django 5.1.15 on 2026-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_harghartirangaregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="harghartirangaregistration",
            name="token_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="token ID",
            ),
        ),
    ]
