# Generated by Django 5.1.15 on 2026-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_harghartirangaregistration_token_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipphotos",
            name="chandaben_patel_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="divya_nikunj_khakhi_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="gautam_patel_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="jayeshbhai_prajapati_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="kiran_raval_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="nirav_joshi_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
        migrations.AddField(
            model_name="leadershipphotos",
            name="vipul_patel_photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
    ]
