# Generated by Django 5.1.15 on 2026-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_leadershipphotos_chandaben_patel_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this record was created (UTC).",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified (UTC).",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "cleanliness_drives",
                    models.PositiveIntegerField(
                        default=212, verbose_name="cleanliness drives"
                    ),
                ),
                (
                    "waste_removed_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=64.0,
                        max_digits=10,
                        verbose_name="waste removed (tons)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Statistics",
                "verbose_name_plural": "Campaign Statistics",
            },
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="divya_nikunj_khakhi_photo",
            new_name="divya_khakhi_photo",
        ),
        migrations.RenameField(
            model_name="leadershipphotos",
            old_name="gautam_patel_photo",
            new_name="jayesh_prajapati_photo",
        ),
        migrations.RemoveField(
            model_name="leadershipphotos",
            name="jayeshbhai_prajapati_photo",
        ),
        migrations.RemoveField(
            model_name="leadershipphotos",
            name="nirav_joshi_photo",
        ),
    ]
